# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blade-deployment
  namespace: blade-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blade
  template:
    metadata:
      labels:
        app: blade
    spec:
      containers:
      - name: bladeservice
        image: __ACR_NAME__.azurecr.io/__APP_NAME__:__TAG__
        imagePullPolicy: Always
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "50m"
        ports:
        - containerPort: 8080
