# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: blade-service
  namespace: blade-namespace
spec:
  type: LoadBalancer
  selector:
    app: blade
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
